### ISSUE TITLE
URL needed massage

### ISSUE THREAD

**Issue by gah242s** [progressivetech/net.ourpowerbase.remoteform#10] opened 2018-12-10 18:34 UTC
Perhaps I have something still mis-configured, but on WordPress I had to change the URL: parameter by removing  wp-admin/admin.php just before the ? character.  After doing so, it went through without a hiccup.

**Comment by jmcclelland** [comment] 2018-12-10 19:14
This is totally untested on wordpress so I'm guessing it's not you. Can you do me a huge favor and paste in both the auto-generated code before you fixed it and after you fixed it? That will help me figure out how to make this work automatically for wordpress users.

**Comment by gah242s** [comment] 2018-12-10 20:45
It doesn't want to let me bold the line.  The only difference is in the line that starts with "url:" inside the script tag.  Here's the single line diff and then the whole blocks after that.

Before:
```  url: "https://siteurl/wp/wp-admin/admin.php?page=CiviCRM&amp;q=civicrm%2Fremoteform", ```
After:
```  url: "https://siteurl/wp/?page=CiviCRM&amp;q=civicrm%2Fremoteform", ```

Before:
``` <!-- The stylesheet link is optional and can be removed 
if you want to style the form yourself, or if you 
already are including a bootstrap css environment. -->
<link rel="stylesheet" property="stylesheet" href="https://siteurl/wp/wp-content/plugins/files/civicrm/ext/net.ourpowerbase.remoteform/remoteform.css">
<div id="remoteForm"></div>
<script src="https://siteurl/wp/wp-content/plugins/files/civicrm/ext/net.ourpowerbase.remoteform/remoteform.js"></script>
<script> var remoteFormConfig = { 
 url: "https://siteurl/wp/wp-admin/admin.php?page=CiviCRM&amp;q=civicrm%2Fremoteform",
 id: 42,
 entity: "Profile",
};
if (typeof remoteForm !== "function") {
  document.getElementById("remoteForm").innerHTML = "Oh no! I was not able to display the form! Please check your security settings (for example Privacy Badger) and allow remote javascript to be displayed from siteurl."
  document.getElementById("remoteForm").style.color = "red";
}
else {
  remoteForm(remoteFormConfig);
}
</script>
```
After:
``` <!-- The stylesheet link is optional and can be removed 
if you want to style the form yourself, or if you 
already are including a bootstrap css environment. -->
<link rel="stylesheet" property="stylesheet" href="https://siteurl/wp/wp-content/plugins/files/civicrm/ext/net.ourpowerbase.remoteform/remoteform.css">
<div id="remoteForm"></div>
<script src="https://siteurl/wp/wp-content/plugins/files/civicrm/ext/net.ourpowerbase.remoteform/remoteform.js"></script>
<script> var remoteFormConfig = { 
 url: "https://siteurl/wp/?page=CiviCRM&amp;q=civicrm%2Fremoteform",
 id: 42,
 entity: "Profile",
};
if (typeof remoteForm !== "function") {
  document.getElementById("remoteForm").innerHTML = "Oh no! I was not able to display the form! Please check your security settings (for example Privacy Badger) and allow remote javascript to be displayed from siteurl."
  document.getElementById("remoteForm").style.color = "red";
}
else {
  remoteForm(remoteFormConfig);
}
</script>
```

**Comment by jmcclelland** [comment] 2018-12-11 15:30
Thanks for the feedback. I think the problem is that I'm not specifying $frontend = TRUE - a setting that is ignore in drupal, but required in wordpress. I just pushed the fix to this git repo. Can you pull a fresh copy and see if that does the trick?

**Comment by gah242s** [comment] 2018-12-11 16:59
Hrm ... Not sure what's going on.  Admittedly, I made the change manually, rather than downloading a new copy, but I had the latest version prior to that.  I've uninstalled, reinstalled, and cleared caches, but it's still giving the same URL.  Is it perhaps the $base_url rather than the $post_url that's causing the issue?

**Comment by gah242s** [comment] 2018-12-11 19:08
For kicks, I re-downloaded, uninstalled, reinstalled, cleared cache and reset paths.  Nothing is changing.  Sorry.

**Comment by gah242s** [comment] 2018-12-13 16:54
For kicks, I re-downloaded, uninstalled, reinstalled, cleared cache and reset paths.  Nothing is changing.  Sorry.

**Comment by jmcclelland** [comment] 2019-01-04 19:05
Is it still showing: url: "https://siteurl/wp/wp-admin/admin.php?page=CiviCRM&amp;q=civicrm%2Fremoteform",

??

**Comment by gah242s** [comment] 2019-01-16 16:03
Sorry I dropped off for a little while.  Infrastructure emergencies.  I downloaded a new copy and am seeing the same behavior.  I'm also see that the Country dropdown is not populating, but I don't see any console errors.  It does populate as expected on the Profile Preview when editing the Profile in CiviCRM.  Not sure where to look for that error.

**Comment by jmcclelland** [comment] 2019-03-05 15:51
Found a mistake in my code - the latest version should work. For the record, the URL should be:

```
url: "https://siteurl/wp/?page=CiviCRM&q=civicrm%2Fremoteform",
```

The & in the middle should not be html-entitized.

Also I fixed the population of states and countries (counties still doesn't work both states and counties should).

**Comment by jmcclelland** [comment] 2019-06-12 18:09
I'm assuming this is now fixed.

**Closed by jmcclelland** 2019-06-12 18:09 UTC
