### ISSUE TITLE
Dedupe rules

### ISSUE THREAD

**Issue by netzih** [progressivetech/net.ourpowerbase.remoteform#13] opened 2019-03-05 19:49 UTC
Dedupe rules not working and all form submissions (profiles and contributions) are creating new contacts.

**Comment by jmcclelland** [comment] 2019-05-16 02:49
Thanks for the report (and sorry for slow reply). Confirmed as bug. I haven't had a chance to fix it yet.

**Comment by netzih** [comment] 2019-05-29 22:02
Thank you.
Let us know when any update is posted.

**Comment by jmcclelland** [comment] 2019-06-12 18:07
Fixed at last with commit c196a5ef2069d7574480c2ef4a14124cb2e3bca3

Please try it out and let me know if de-duping now works.

**Comment by netzih** [comment] 2019-06-18 00:56
I tried and it is still creating another contact.
I deleted the old remote form folder from EXT folder and unzipped the new one.
Is there maybe something else I need to do?

**Comment by netzih** [comment] 2019-06-18 02:35
Just tried it on another site that did not have remote forms installed and it's creating duplicate contacts.

**Comment by jmcclelland** [comment] 2019-06-18 14:34
Oh - I see. I didn't make a new release yet. Try downloading and replacing these two files:

https://github.com/progressivetech/net.ourpowerbase.remoteform/raw/master/remoteform.js

The file should replace the one called "remoteform.js" in the main extension directory.

And...

https://github.com/progressivetech/net.ourpowerbase.remoteform/raw/master/CRM/Remoteform/Page/RemoteForm.php

Should replace the file called RemoteForm.php in CRM/Remoteform/Page/ directory.

**Comment by netzih** [comment] 2019-06-19 01:05
> Oh - I see. I didn't make a new release yet. Try downloading and replacing these two files:
> 
> https://github.com/progressivetech/net.ourpowerbase.remoteform/raw/master/remoteform.js
> 
> The file should replace the one called "remoteform.js" in the main extension directory.
> 
> And...
> 
> https://github.com/progressivetech/net.ourpowerbase.remoteform/raw/master/CRM/Remoteform/Page/RemoteForm.php
> 
> Should replace the file called RemoteForm.php in CRM/Remoteform/Page/ directory.

Tried unsuccessfully.
I changed those 2 files (deleted the old one and downloaded this one in it's place) and still creating new contacts.
I thought maybe my dedupe rules are off but when submitting the profiles on the site itself (without remote forms) it's not creating a new contact.

**Comment by netzih** [comment] 2019-06-19 01:05
Still love the extension. Thank you for it.

**Comment by jmcclelland** [comment] 2019-06-19 14:07
Oh no. I'm going to start by re-opening this issue and take a closer look. Thanks for the feedback.

**Comment by jmcclelland** [comment] 2019-06-19 14:47
Wow, I clearly did not properly test this fix - thanks again for the feedback.

I found and fixed two bugs:

1. The dedupe checker was testing if the number of dupes was > 1 (it should be testing if the number of dupes is > 0).
2. The javascript was submitting each form twice instead of once. That means it was creating two dupes not just one

Both should now be fixed (if you follow the same instructions to manually replace those two files). 

If it works for you, I'll release a new version.

**Comment by netzih** [comment] 2019-06-19 21:08
> Wow, I clearly did not properly test this fix - thanks again for the feedback.
> 
> I found and fixed two bugs:
> 
> 1. The dedupe checker was testing if the number of dupes was > 1 (it should be testing if the number of dupes is > 0).
> 2. The javascript was submitting each form twice instead of once. That means it was creating two dupes not just one
> 
> Both should now be fixed (if you follow the same instructions to manually replace those two files).
> 
> If it works for you, I'll release a new version.

Works.
Thank you !!

**Comment by jmcclelland** [comment] 2019-06-21 14:52
Excellent! Thanks for the help closing this one out.

**Comment by netzih** [comment] 2019-07-09 22:41
Not sure what's going on.
Tried to install remote forms on another site and dedupe was not working again. manually replaced those 2 files and it still is creating new contacts...
Did something change?

**Comment by netzih** [comment] 2019-07-09 23:05
> Not sure what's going on.
> Tried to install remote forms on another site and dedupe was not working again. manually replaced those 2 files and it still is creating new contacts...
> Did something change?

I even copied the whole extension folder as is from the site that is working to the new site but it is creating a new contact.

**Comment by jmcclelland** [comment] 2019-07-10 17:26
remoteforms should be respecting the dedupe setting on the profile itself. Is it possible the profile on your new site has 'What to do upon duplicate match' set to 'Allow duplicate contact to be created'?

**Comment by netzih** [comment] 2019-07-10 17:29
I created a profile under use profile and it updated matching contact (as set in the settings) only the remote form is creating new contacts.
Can I be missing something?

**Comment by jmcclelland** [comment] 2019-07-10 20:27
I'm baffled by this one too. If you want to share the link to where your remote form is hosted I can take a look and see if I notice anything suspicious. Otherwise I'm not sure what step to take next.

**Comment by netzih** [comment] 2019-07-10 20:33
Is there a way to send it privately? I'd prefer not to post it publicly.

**Comment by netzih** [comment] 2019-07-10 20:39
Whatever. It's on chabadcape.com on the bottom of the homepage in footer area 2

**Comment by jmcclelland** [comment] 2019-07-10 20:58
Just a guess... what if you disable the note field?

**Comment by netzih** [comment] 2019-07-10 20:59
The note is the same as on the other site and doesn't cause any issues there.

**Comment by jmcclelland** [comment] 2019-07-26 14:15
I'm still curious about the note field - just as a test.... but generally i'm still baffled as well.

**Comment by netzih** [comment] 2019-07-26 17:40
Just tested it without the Note field and it still created a new contact.

**Comment by jmcclelland** [comment] 2019-07-26 19:44
ok, thanks for checking. still stumped on this one.

**Comment by urlisse** [comment] 2019-09-11 19:37
I may have a hint about what's going wrong with deduping here... It has to do with case sensitivity.

I had this case where `RemoteForm` was requesting a dedupe on a field name `email-primary`, but the  `CRM_Dedupe_Finder` would ignore this field because it wasn't named `email-Primary`, and the dedupe could not occur.

A brutal patch would be to make the `preg_match` in its [`formatParams` function](https://lab.civicrm.org/dev/core/blob/d434a5cfb2dc3c248ac3c0d8570bd8e9d828f6ad/CRM/Dedupe/Finder.php#L281) case  insensitive, like this:

```php
preg_match('/(.*)-(Primary-[\d+])$|(.*)-(\d+|Primary)$/i
```

However, it might be best just to make sure that parameter names aren't transformed to lower case before attempting to dedupe them.

**Comment by netzih** [comment] 2019-09-11 22:43
> I may have a hint about what's going wrong with deduping here... It has to do with case sensitivity.
> 
> I had this case where `RemoteForm` was requesting a dedupe on a field name `email-primary`, but the `CRM_Dedupe_Finder` would ignore this field because it wasn't named `email-Primary`, and the dedupe could not occur.
> 
> A brutal patch would be to make the `preg_match` in its [`formatParams` function](https://lab.civicrm.org/dev/core/blob/d434a5cfb2dc3c248ac3c0d8570bd8e9d828f6ad/CRM/Dedupe/Finder.php#L281) case insensitive, like this, in civicrm-core:
> 
> ```
> if (preg_match('/(.*)-(Primary-[\d+])$|(.*)-(\d+|Primary)$/i', $key, $matches)) {
> ```
> 
> However, it might be best just to make sure that parameter names aren't transformed to lower case before attempting to dedupe them.

Thank you.
I'm not sure I'm comfortable with playing with core files...

Thank you

**Comment by jmcclelland** [comment] 2019-10-11 21:04
I'm re-opening - I'm also seeing certain conditions where the deduping is not working. I haven't dug in more to see if it's for the reasons idenfified by @urlisse but will certainly be looking there first.

**Closed** 2024-06-07 15:35 UTC

**Comment by jmcclelland** [comment] 2024-06-07 15:37
Thanks to @mlutfy this is hopefully resolved. I think there may be conditions when the fields names have different cases? In any event, this fix should cover all possible scenarios.
